blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('category/', views.category_list, name='category_list'),
    path('category/create/', views.category_create, name='category_create'),
    path('category/<category_slug>/', views.post_list, name='post_list_by_category'),
    path('post/<slug>/<int:id>/', views.post_detail, name='post_detail'),
    path('post/<slug>/<int:id>/edit/', views.post_edit, name='post_edit'),
    path('post/create/', views.post_create, name='post_create'),
    path('comment/<slug>/<int:id>/comment/create/', views.comment_create, name='comment_create'),
    path('comment/<slug>/<int:id>/comment/<int:comment_id>/edit/', views.comment_edit, name='comment_edit'),
    path('comment/<slug>/<int:id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import RedirectView

# def root(request):
#    return redirect('blog:post_list')


urlpatterns = [
    # path('', root, name='root'),
    # path('', lambda r: redirect('blog:post_list'), name='root'),
    path('', RedirectView.as_view(pattern_name='blog:post_list'), name='root'),
    path('admin/', admin.site.urls),
    # namespcae를 지정하면 항상 사용해야한다. 사용하지 않으면 error발생
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

blog/models.py
from django import forms
from django.db import models
from django.urls import reverse
from django.conf import settings
import re

# Create your models here.

def _get_slug(self, words):
    split_words = re.split('[\W]+', words)
    slug = []
    slugify = ''
    for word in split_words:
        if word:
            slug.append(word)
    slugify = '-'.join(slug)
    return slugify


class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True, allow_unicode=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_slug(name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('blog:post_list_by_category', args=[self.slug])


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


def min_length_3_validator(value):
    if len(value) < 3:
        raise forms.ValidationError('3글자 이상 입력해주세요')


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='posts')
    # 'auth.User' 엡이름.모델
    # setting.AUTH_USER_MODEL: 사용자 인증에 사용되는 User모델이 변경됐을 경우 자동 대응
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100)
    content = models.TextField(validators=[min_length_3_validator])
    # Tag 클래스로 지정 or 'Tag' 문자열 형태로 걸 수 있다 그러면 Tag모델이 post 뒤에 있어도 사용할 수 있다.
    # manytomany일 경우 blank option을 선호
    Tags = models.ManyToManyField('Tag', blank=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)
    Comments = models.PositiveSmallIntegerField(default=0, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(blank=True, null=True)
    image = models.ImageField(default='default.png', upload_to='post/%Y/%m/%d', blank=True)
    ip = models.GenericIPAddressField(null=True)


    class Meta:
        ordering = ['-created']
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def publish(self):
        self.published = timezone.now()
        self.save()

    # def save_tags(self):
    #     if not self.Tags:
    #         return
    #     tags_list = []
    #     # 입력된 값들을 # 구분자로 구분한 후 공백 제거
    #     tags = map(lambda str: str.strip(), unicode(self.Tags).split('#'))
    #     # TagModel DB에서 입력된 값들을 가져오거나 없으면 생성
    #     for tag in tags:
    #         tag = Tags.objects.get_or_create(name=tag)[0]
    #         self.Tags.add(tag)
    #     # tags_list = [TagModel.objects.get_or_create(name=tag)[0] for tag in tags]
    #     # # Tags를 리스트 형태로 반환
    #     # self.Tag.add(*tag_list)

    def _get_slug(self):
        split_title = re.split('[\W]+', self.title)
        slug = []
        slugify = ''
        for word in split_title:
            if word:
                slug.append(word)
        slugify = '-'.join(slug)
        return slugify

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_slug()
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug, self.id])


class Comment(models.Model):
    # Post : Comment = 1:N
    post = models.ForeignKey('post', on_delete=models.CASCADE, null=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    message = models.TextField(max_length=2000, null=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_public = models.BooleanField(default=False)
    ip = models.GenericIPAddressField(null=True)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.message

blog/forms.py
from django import forms
from .models import *



class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['name']


class PostForm(forms.ModelForm):
    # category = forms.ChoiceField(widget=forms.Select(attrs={'class':'form-control'}))
    # title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    # title = forms.CharField(widget=forms.TextInput(validators=[min_length_3_validator]))
    # content = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    # Tags = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    # def __init__(self, *args, **kwargs):
    #     super(PostForm, self).__init__(*args, **kwargs)
    #     self.fields['category'].widget.choices = Category.objects.all()

    category = forms.ModelChoiceField(queryset=Category.objects.all().order_by('name'), widget=forms.Select(attrs={
        'class':'btn dropdown-toggle bs-placeholder select-with-transition', 
        'data-toggle':'dropdown',
        'role': 'button',}))
        
    title = forms.CharField(label='제목', help_text='제목을 적어주세요', widget=forms.TextInput(attrs={
        'class':'form-control',
    }))
    content = forms.CharField(label='내용', help_text='100 characters max.', widget=forms.Textarea(attrs={
        'class': 'form-control',        
        'rows': 5,
        'cols': 50,
        'size': '70px',
        'placeholder': '', }))
    
    class Meta:
        model = Post
        fields = ['category', 'title', 'content']

class CommentForm(forms.ModelForm):
    message = forms.CharField(label='', widget=forms.TextInput(attrs={
        'class': 'comment-form',
        'size': '70px',
        'placeholder': '댓글 달기...',
        'maxlength': '40', }))

    class Meta:
        model = Comment
        fields = ['message']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *

# Create your views here.

def category_list(request):
    categories = Category.objects.all()

    return render(request, 'blog/category_list.html', {'categories':categories})


def category_create(request):
    if request.method =='POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = Category(**form.cleaned_data)
            category.save()
            messages.info(request, '새 분류가 등록되었습니다.')
            return redirect('blog:category_list')
    else:
        form = CategoryForm()
    
    return render(request, 'blog/category_form.html', {'form': form})


def post_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()

    posts = Post.objects.all()
    posts = posts.order_by('created')

    # 검색 조건이 있으면 제목에서 해당 내용을 찾는다.
    q = request.GET.get('q', '')
    if q:
        posts = posts.filter(title__icontains=q)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        posts = posts.filter(category=category)

    paginator = Paginator(posts, 10)

    page = request.GET.get('page')
    posts = paginator.get_page(page)

    return render(request, 'blog/post_list.html', {'category':category, 'categories':categories, 'posts':posts})


def post_detail(request, slug, id):
    post = get_object_or_404(Post, slug=slug, id=id)

    def get_previous_post(self):
        return self.get_previous_by_updated()

    def get_next_post(self):
        return self.get_next_by_updated()

    return render(request, 'blog/post_detail.html', {'post': post})

@login_required
def post_create(request):
    # POST 요청에 의해 서버로 입력 값을 전송하기 전에 검증
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        # 입력 값 검증
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.created = timezone.now()
            post.ip = request.META['REMOTE_ADDR']
            print(form.cleaned_data)
            post = Post(**form.cleaned_data)
            post.save()
            # post.save_tags()
            messages.info(request, '새 글이 등록되었습니다.')
            return redirect('blog:post_detail', post.slug, post.id)
        else:
            form.errors
    else:
        # 글을 새로 생성하려면 폼을 띄워주고(GET), 입력 값 검증에 문제 발생시 form.error에 오류 정보를 저장.
        form = PostForm()
    return render(request, 'blog/post_form.html', {'form': form})

@login_required
def post_edit(request, slug, id):
    post = get_object_or_404(Post, slug=slug, id=id)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=Post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.updated = timezone.now()
            post.save()
            return redirect('blog:post_detail', post.slug, post.id)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {'form': form})


@login_required
def comment_create(request, slug, id):
    post = get_object_or_404(Post, slug=slug, id=id)
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.ip = request.META['REMOTE_ADDR']
            #comment = Comment(**form.cleaned_data)
            comment.save()
            messages.info(request, '새 글이 등록되었습니다.')
            return redirect('blog:post_detail', post.slug, post.id)
        else:
            form.errors()
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})

@login_required
def comment_edit(request, slug, id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.author != request.user:
        #return redirect('blog:post_detail', slug, id)
        return redirect(comment.post)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES, instance=comment)
        if form.is_valid():
            comment = form.save()
            return redirect(comment.post)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'blog/comment_form.html', {'form':form,})

@login_required
def comment_delete(request, slug, id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.author != request.user:
        return redirect(comment.post)

    if request.method == "POST":
        comment.delete()
        return redirect(comment.post)

    return render(request, 'blog/comment_confirm_delete.html', {'comment':comment,})

blog/templates/blog/category_form.html
{% extends 'blog/post_base.html' %}
{% load staticfiles %}
{% block post %}
<script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
<!-- Material Design icon font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
<!-- Simple Textfield -->
<form method='POST'>
  {% csrf_token %}
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <input class="mdl-textfield__input" type="text" id="sample1">
    <label class="mdl-textfield__label" for="sample1">Category...</label>
  </div>
  <button type="submit" class="save btn btn-default">Save</button>
</form>

{%  comment %}
<!-- Numeric Textfield -->
<!-- <form action="#">
  <div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" type="text" pattern="-?[0-9]*(\.[0-9]+)?" id="sample2">
    <label class="mdl-textfield__label" for="sample2">Number...</label>
    <span class="mdl-textfield__error">Input is not a number!</span>
  </div>
</form> -->
{% endcomment %}
{% endblock post %}

blog/templates/blog/category_list.html
{% extends 'blog/post_base.html' %}
{% load staticfiles %}

{% block post %}
{% for category in categories %}
    <div>
        <h1>{{ category }}</h1>
    </div>
{% endfor %}
{% endblock post %}

blog/templates/blog/comment_confirm_delete.html
<form action="" method="POST">
    {% csrf_token %}
    정말 삭제하시겠습니까?
    <input type="submit" value="삭제하겠습니다." />
</form>

blog/templates/blog/comment_form.html
{% extends 'blog/post_base.html' %}

{% block post %}
<form action="" method='POST'>
    {% csrf_token %}
    <table>  {{ form.as_table }}
    </table>
    <input type="submit">
</form>
{% endblock post%}

blog/templates/blog/post_base.html
{% extends 'SEO.html' %}

{% load staticfiles %}
{% block content%}
    
{% block post %}

{% endblock post %}

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/post_base.html' %}
{% load staticfiles %}

{% block post %}
<style>
    p {
        font-size: 19px;
    }
</style>
<div class="col-12">
    <div class="post">
        {% if post.published %}
            <div class="date">
                {{ post.published }}
            </div>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.content |linebreaksbr }}</p>
    </div>
    <hr>
    <div class="title">
        <h3>댓글</h3>
    </div>
    <a href="{% url 'blog:comment_create' post.slug post.id %}" class="pull-right">
        <i class="material-icons">add</i>댓글 추가
    </a>
    
    <hr />
    <ul>
        {% for comment in post.comment_set.all %}
        <li> 
            {{ comment.message }}
            <small>by {{ comment.author }}</small>
            <small>at {{ comment.created }}</small>
            {% if comment.author == request.user %}
            <a href="{% url "blog:comment_edit" post.slug post.id comment.id %}">수정</a>
            <a href="{% url "blog:comment_delete" post.slug post.id comment.id %}" class="text-danger">삭제</a>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
    <hr>
    <a href="{% url "blog:post_list" %}" class='btn btn-primary'>글 목록</a>
    <a href="{% url "blog:post_edit"  post.slug post.id %}" class='btn btn-default'>수정</a>
</div>
{% endblock post%}

blog/templates/blog/post_form.html
{% extends 'blog/post_base.html' %}

{% block post %}
<form method='POST'>
    {% csrf_token %}
    <div class="container">
        <!--div class="row"-->
    {% for error in form.non_field.errors %}
    <div class="alert alert-danger">
            {{ error }}
    </div>
    {% endfor %}

    {% for field in form.hidden_fields %}
        {{ field }}
    {% endfor %}

    {% for field in form.visible_fields %}
            <div class="col-md-6 col-md-offset-3">
                <div class="form-group">
                    <label for="{{ field.auto_id }}" class="bmd-label-floating">
                        {{ field.label }}
                    </label>
                    {{ field }}
                    {% if field.help_text %}
                        <span class="bmd-help">{{ field.help_text }}</span>
                    {% endif %}
                </div>
            </div>
    
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    <hr>
    <button type="submit" class="save btn btn-default">저장</button>
</div>
    <!-- <table>  
        {{ form.as_table }}
    </table> -->
    <!-- <div class="row">
    <div class="justify-content-center">
        <div class="col-sm-6"></div>
    </div>
    <input type="submit"-->
</form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/post_base.html' %}
{% load staticfiles %}

{% block post %}
<div class="jumbotron">
    <h1>SafeWeb<sup><small>powered by Django</small></sup></h1>
    <p>안전한 인터넷 사용을 위한 기술들</p>
    <p>
        <a class="btn btn-lg btn-primary" href="https://www.isecurekr.com">아이시큐어 &raquo;</a>
    </p>
</div>
<div class="container">

<div class="row">
    <div class="col-md-12">
        <div class="title">
            <h3>카테고리</h3>
        </div>
        <nav class="navbar navbar-expand-lg bg-white">
            <div class="container">
                <div class="navbar-translate">
                    <a class="navbar-brand"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        <span class="navbar-toggler-icon"></span>
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav">
                        <li class="nav-item {% if not category %}active{% endif %}">
                            <a href="{% url 'blog:post_list' %}" class="nav-link">All</a>
                        </li>
                        {% for c in categories %}
                        <li class="nav-item {% if category.slug == c.slug %}active{% endif %} ">
                            <a href="{{ c.get_absolute_url }}" class="nav-link">{{ c.name }}</a>
                        </li>
                        {% endfor %}
                        <!-- <li class="dropdown nav-item">
                            <a href="#pablo" class="dropdown-toggle nav-link" data-toggle="dropdown">Dropdown</a>
                            <div class="dropdown-menu">
                                <h6 class="dropdown-header">Dropdown header</h6>
                                <a href="#pablo" class="dropdown-item">Action</a>
                                <a href="#pablo" class="dropdown-item">Another action</a>
                                <a href="#pablo" class="dropdown-item">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a href="#pablo" class="dropdown-item">Separated link</a>
                                <div class="dropdown-divider"></div>
                                <a href="#pablo" class="dropdown-item">One more separated link</a>
                            </div>
                        </li> -->
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>
<a href="{% url 'blog:post_create' %}" class="pull-right"><i class="material-icons">add</i>새글쓰기</a>

<form class="form-inline" action="" method="get">
    <div class=" has-black">
        <input type="text" class="form-control" name="q" value="{{ q }}" />
        <button type="submit" class="btn btn-white btn-raised btn-fab btn-round" />
            <i class="material-icons">search</i>
        </button>
    </div>
</form>


{% for post in posts %}
    <div>
        <h1>
            <a href=" {% url 'blog:post_detail' slug=post.slug id=post.id %}">{{ post.title }}</a>
        </h1>
        <p>{{ post.content|truncatewords:10 }}</p>
        <p>update: {{ post.updated|date:"D d M Y" }}</p>
    </div>
{% endfor %}

<div class="title">
    <h3>댓글</h3>
</div>
<hr />
<ul>
    {{ comment }}
    {% for comment in post.comment_set.all %}
    <li>
        {{ comment.content }}
        <small>by {{ comment.author }}</small>
        <small>at {{ comment.create }}</small>
    </li>
{% endfor %}
</ul>

{% endblock post %}